name = "GitHub Actions"
grammar = "yaml"
path_suffixes = ["yml", "yaml"]
line_comments = ["# "]
tab_size = 2
hard_tabs = false

[[brackets]]
start = "{"
end = "}"
close = true
newline = true

[[brackets]]
start = "["
end = "]"
close = true
newline = true

[[brackets]]
start = "\""
end = "\""
close = true
newline = false

[[brackets]]
start = "'"
end = "'"
close = true
newline = false
